image: publysher/hugo

pages:
  script:
  - cd site
  - sed  -i 's/baseurl = "\/"/baseurl = "https:\/\/frv.frama.io\/bbb-utils\/"/' config.toml
  artifacts:
    paths:
    - site/public
  only:
  - master
variables:
  GIT_SUBMODULE_STRATEGY: normal

